### ISSUE TITLE
How to Connect the Robot's Computer?

### ISSUE THREAD

**Issue by BeNavon** [machines-in-motion/Go2Py#8]
The instructions mention: "Now tell the computer on the robot to use the internet shared by the host computer."
I am seeking guidance on how to connect the computer on the robot to utilize the internet connection shared by the host computer.

**Comment by BeNavon** [comment]
> Can you please be a bit more specific about the issue? Have you followed through the instructions [here](https://github.com/machines-in-motion/Go2Py/blob/main/docs/setup.md)?

Can you please be a bit more specific about the issue? Have you followed through the instructions [here](https://github.com/machines-in-motion/Go2Py/blob/main/docs/setup.md)?

**Comment by Rooholla-KhorramBakht** [comment]
Follow through the instructions on your previous issue [here](https://github.com/machines-in-motion/Go2Py/issues/10#issuecomment-2483671311) and you should be able to use the simulator. You can also install the repository locally by running pip install -e . and the notebook should work.
